#Example AC Config
#Example AC uses actions.
#
#Supports PlaceholderAPI https://www.spigotmc.org/resources/placeholderapi.6245/
#
#Placeholders are: %player% %tps% %ping% %check% %sub-check% (only in case under sub-checks) %vl% %nick%

#Update checker will check to see if there is an update for example.
update_checker:

    #Is the update checker enabled?
    enabled: true

    #Check interval.
    #Measured in ticks. 1 second = 20 ticks. 1 minute = 1200 ticks. 1 hour = 72000 ticks.
    time: 12000
    
#Time for the good stuff. Checks.
checks:
    killaura:
        enabled: true
        nick: KillAura
        modules:
            SelfHit:
                enabled: true
                violation-add: 30
                actions: {}
            Reach:
                enabled: true
                #Max reach distance
                max_reach: 3.2
                violation-add: 8
            Analyzer:
                enabled: true
                Accuracy:
                    enabled: true
                    #The minimum amout of movement before this check will check the player. Mesured in blocks. Can be decimal.
                    min-movement: 2.375
                    #Percentage of hits before adding to the violations.
                    percentage: 40
                    violation-add: 9
                Aimbot:
                    enabled: true
                    #How strict should the patern recognition be? The stricter it is, the less it will flag, but the less strict it is, the more it will false. 0 will flag everybody. 100 will only flag really shitty aimbots.
                    strict: 75
                    #Percentage of hits before adding to the violations.
                    percentage: 40
                    violation-add: 15
            cancel-vl: 70
            action: 
            10:
            - "example notify %player% IS USING AURA!!!!!!!!! %tps% %ping% %vl%"
            
    speed:
            enabled: true
            nick: Speed
            modules:
                limit:
                    enabled: true
                    #Maximum bps (blocks per second) the player can go.
                    max-bps: 6
                    violation-add: 14
                timer:
                    enabled: true
                    #Maximum timer the player can have.
                    max-timer: 1.08
                    #Minimum timer the player can have.
                    min-timer: 0.97
                    #Maximum pps (packets per second) the player can send. I actually don't know, so ac devs, pls insert this number.
                    max-pps: 100
                    #Minimum pps (packets per second) the player can send. I actually don't know, so ac devs, pls insert this number.
                    min-pps: 10
                    violation-add: 14
                low-hop:
                    enabled: true
                    #Maximum blocks the player can jump. This is the EXACT value of minecraf
                    max-blocks-height: 1.24918707874468
                    #Minimum blocks the player can jump. 
                    min-blocks-height: 1.249                        
                violation-need: 100
                g-violation-add: 10
                action: %vl%=1:cancel:example notify %player% might be using %hack%.
#This is the end of this example. I might add more(? Maybe), but you get the concept of the config.
