#Example AC Config
#Example AC uses actions.
#
#Supports PlaceholderAPI https://www.spigotmc.org/resources/placeholderapi.6245/

#Update checker will check to see if there is an update for example.
update_checker:

    #Is the update checker enabled?
    enabled: true

    #Check interval.
    #Measured in ticks. 1 second = 20 ticks. 1 minute = 1200 ticks. 1 hour = 72000 ticks.
    time: 12000
    
#Time for the good stuff. Checks.
checks:
#example check
#Most checks will follow this patern. If it has something that isn't here, it will be explained there.
#    check:
#Is the check enabled?
#        enabled: true
#Check name for %hack%
#        name: Check
#You can set all the parameters here
#        modules:
#Module
#            module:
#Is the check enabled?
#                enabled: true
#Amount it will add to violations.
#                violation-add: 1
#How many violations will this check need to add to the global violations?
#        violation-need: 100
#How many violations will this check add to the global violations?
#        g-violation-add: 10
#Actions.
#        action: 
#             -
    killaura:
        enabled: true
        name: KillAura
        modules:
            SelfHit:
                enabled: true
                violation-add: 30
            Reach:
                enabled: true
                #Max reach distance
                max_reach: 3.2
                violation-add: 8
            Analyzer:
                enabled: true
                Accuracy:
                    enabled: true
                    #The minimum amout of movement before this check will check the player. Mesured in blocks. Can be decimal.
                    min-movement: 2.375
                    #Percentage of hits before adding to the violations.
                    percentage: 40
                    violation-add: 9
                Aimbot:
                    enabled: true
                    #How strict should the patern recognition be? The stricter it is, the less it will flag, but the less strict it is, the more it will false. 0 will flag everybody. 100 will only flag really shitty aimbots.
                    strict: 75
                    #Percentage of hits before adding to the violations.
                    percentage: 40
                    violation-add: 15
            
            violation-need: 200
            g-violation-add: 15
            action: %vl%=70:cancel:%vl%=90:example notify %player% might be using killaura.:%vl%=120:example notify %player% is probably using killaura. %vl%=300: example kick %player% You have been kicked because of suspicious attack.
            
    speed:
            enabled: true
            name: Speed
            modules:
                limit:
                    enabled: true
                    #Maximum bps (blocks per second) the player can go in the air. Usage: 3t:7.7,10t:6.8,5.7 would be 3ticks in the air, the max would be 7.7 bps, then 10 ticks, max 6.8, then max 5.7 bps.
                    max-bps: 3t:7.7,10t:6.8,5.7
                    violation-add: 14
                timer:
                    enabled: true
                    #Maximum timer the player can have.
                    max-timer: 1.08
                    #Minimum timer the player can have.
                    min-timer: 0.97
                    #Maximum pps (packets per second) the player can send. I actually don't know, so ac devs, pls insert this number.
                    max-pps: 100
                    #Minimum pps (packets per second) the player can send. I actually don't know, so ac devs, pls insert this number.
                    min-pps: 10
                    violation-add: 14
                low-hop:
                    enabled: true
                    #Maximum blocks the player can jump. This is the EXACT value of minecraf
                    max-blocks-height: 1.24918707874468
                    #Minimum blocks the player can jump. 
                    min-blocks-height: 1.249                        
                violation-need: 100
                g-violation-add: 10
                action: %vl%=1:cancel:example notify %player% might be using %hack%.
#This is the end of this example. I might add more(? Maybe), but you get the concept of the config.
